services:
  ctfd:
    build: .
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SECRET_KEY=CHANGE_ME_RANDOM_VALUE
    volumes:
      - ctfd_logs:/var/log/CTFd
      - ctfd_uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      permissions:
        condition: service_completed_successfully
      db:
        condition: service_started
      cache:
        condition: service_started
    networks:
      - default
      - internal
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ctfd.rule=Host(`ctfd.briceprivat.works`)"
      - "traefik.http.routers.ctfd.entrypoints=websecure"
      - "traefik.http.routers.ctfd.tls.certResolver=letsencrypt"
      - "traefik.http.routers.ctfd.service=ctfd-service"
      # HTTP → HTTPS redirect
      - "traefik.http.routers.ctfd-http.rule=Host(`ctfd.briceprivat.works`)"
      - "traefik.http.routers.ctfd-http.entrypoints=web"
      - "traefik.http.middlewares.ctfd-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ctfd-http.middlewares=ctfd-redirect"
      # Service
      - "traefik.http.services.ctfd-service.loadbalancer.server.port=8000"

  # TODO: CTFd 4.0 Migrate to named volumes. Users will likely need to manually migrate existing files
  permissions:
    image: alpine:3.23
    user: root
    volumes:
      - ctfd_logs:/var/log/CTFd
      - ctfd_uploads:/var/uploads
    command: chown -R 1001:1001 /var/uploads /var/log/CTFd

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ctfd_mysql:/var/lib/mysql
    networks:
      - internal
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
      - ctfd_redis:/data
    networks:
      - internal

networks:
  default:
  internal:
    internal: true
  dokploy-network:
    external: true

volumes:
  ctfd_logs:
  ctfd_uploads:
  ctfd_mysql:
  ctfd_redis:
